# -*- mode: ruby -*-
# vi: set ft=ruby :

host_home_dir = "~"
home_dir = "/home/vagrant"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_check_update = false
    config.vm.network "public_network", bridge: [
       "en0: Wi-Fi (AirPort)",
       "wlo1",
    ]

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end

    config.ssh.insert_key = true
    config.vm.provision "file", source: "#{host_home_dir}/.ssh/id_rsa.pub", destination: "#{home_dir}/.ssh/me.pub"
    config.vm.provision :shell, inline: "cat #{home_dir}/.ssh/me.pub >> #{home_dir}/.ssh/authorized_keys"

    config.vm.define "first" do |first|
       first.vm.network "private_network", ip: "10.10.10.11"
    end

    config.vm.define "second" do |second|
       second.vm.network "private_network", ip: "10.10.10.12"
    end

    config.vm.define "third" do |third|
       third.vm.network "private_network", ip: "10.10.10.13"
    end
end

